# Our migration files are what create our tables for us. Using Rake, we're able to create our tables very quickly. 
# This file was autogenerated by the Rake command `rake db:create_migration NAME=create_tweets`

class CreateTweets < ActiveRecord::Migration # Our classname here needs to match our filename and should describe what the file is doing. Since we're creating a table called tweets, 
  
  # Our "up" method performs our action - in this case, we'll use it to create a table called `tweets`. 
  # The name of the table is very important - since we have a model called "Tweet", we need a table called "tweets". 
  # ActiveRecord uses these naming conventions to match up models to tables. If we have a model called "Dog", ActiveRecord will associate it a table called "dogs". If we have a model called "Wolf", ActiveRecord will associate it with a table called "wolves" - yes, ActiveRecord is smart and has the plural versions of a bunch of words programmed into it. 

  def up
    create_table :tweets do |t| # this block will add the columns to our table. We use 't' by convention to stand for 'table'
      t.string :username #we're adding two columns to our table, both strings. 
      t.string :status
    end
  end

  # Our "down" method is what we'll use to undo our "up" method if needed. In general, the "down" method should be the opposite of the "up" method - in this case, "drop_table"
  def down
    drop_table :tweets
  end
end
